version: "3.8"
services:
  nba-client:
    image: client
    container_name: client-dc
    ports:
      - 3000:3000
    build:
      context: ./client
      dockerfile: Dockerfile
    command: sh -c "yarn && yarn build"
    volumes:
      - './client:/usr/app'
      - '/usr/app/node_modules'
    environment:
      - .env
      # or
      - CHOKIDAR_USEPOLLING=true
  nba-server:
    image: server
    container_name: server-dc
    ports:
      - 3000:3000
    build:
      context: ./server
      dockerfile: Dockerfile
    command: sh -c "yarn && yarn build"
    volumes:
      - './server:/usr/app'
      - '/usr/app/node_modules'
    environment:
      - .env
      # or
      - CHOKIDAR_USEPOLLING=true
  